<script setup lang="ts">
import TripNav from '../../components/TripNav.vue';
import {computed,ref} from 'vue';import {onLoad} from '@dcloudio/uni-app';import {initialize,findTrip,go,saveTrip,notify,confirm,state} from '../../state';import {balances,yuan} from '../../domain/money';import {clone,uid} from '../../domain/types';import {today} from '../../domain/dates';
const id=ref(''),date=ref('');const trip=computed(()=>findTrip(id.value));const total=computed(()=>trip.value?.expenses.reduce((s,e)=>s+e.amount,0)||0);const net=computed(()=>trip.value?balances(trip.value):{});const categories=computed(()=>{const groups:Record<string,number>={};trip.value?.expenses.forEach(e=>groups[e.category]=(groups[e.category]||0)+e.amount);return Object.entries(groups);});const expenses=computed(()=>[...(trip.value?.expenses||[])].sort((a,b)=>b.date.localeCompare(a.date)));const names=(member:string)=>trip.value?.members.find(m=>m.id===member)?.name||'';
onLoad(async q=>{id.value=q?.id||'';date.value=q?.date||'';await initialize();});
async function settle(){if(!trip.value)return;const from=trip.value.members.find(m=>net.value[m.id]<0),to=trip.value.members.find(m=>net.value[m.id]>0);if(!from||!to)return;const amount=-net.value[from.id];if(!await confirm('记录已结清',`确认 ${from.name} 已实际转给 ${to.name} ¥${yuan(amount)}？此操作只记账，不会发起转账。`))return;try{const t=clone(trip.value);t.settlements.push({id:uid(),from:from.id,to:to.id,amount,date:today()});await saveTrip(t);}catch(e){notify(e);}}
async function undo(id:string){if(!trip.value||!await confirm('撤销结清记录','撤销后会重新显示待结算金额。'))return;try{const t=clone(trip.value);t.settlements=t.settlements.filter(s=>s.id!==id);await saveTrip(t);}catch(e){notify(e);}}
</script>
<template><view class="screen" v-if="trip"><view class="row"><text class="eyebrow">LITTLE SPENDS, GREAT MEMORIES</text><text class="badge">{{trip.expenses.length}} 笔</text></view><view class="title">旅行的每一笔</view><view class="subtitle">{{trip.title}}</view>
<view class="budget-card section"><text class="budget-label">本次旅行总花费</text><view class="budget-total">¥{{yuan(total)}}</view><view class="row"><text>预算 {{trip.budget?'¥'+yuan(trip.budget):'未设置'}}</text><text v-if="trip.budget">{{total>trip.budget?'超出':'剩余'}} ¥{{yuan(Math.abs(trip.budget-total))}}</text></view><view v-if="trip.budget" class="progress"><view :style="{width:Math.min(100,total/trip.budget*100)+'%'}"/></view></view>
<view class="card section"><view class="two-col"><view v-for="m in trip.members" :key="m.id"><text class="subtitle">{{m.name}} · 已支付</text><view class="member-amount">¥{{yuan(trip.expenses.filter(e=>e.payer===m.id).reduce((s,e)=>s+e.amount,0))}}</view><view class="subtitle">承担 ¥{{yuan(trip.expenses.reduce((s,e)=>s+(e.shares[m.id]||0),0))}}</view><view class="net">{{net[m.id]>0?'待收':net[m.id]<0?'待付':'已平衡'}} {{net[m.id]?'¥'+yuan(Math.abs(net[m.id])):''}}</view></view></view><button v-if="trip.members.length===2&&Object.values(net).some(n=>n!==0)" class="secondary small section" :disabled="state.busy||state.readOnly||!state.ready" @click="settle">已实际转账，记录结清</button></view>
<view class="pill-row section"><view class="pill" v-for="[category,amount] in categories" :key="category">{{category}} ¥{{yuan(amount)}}</view></view>
<view class="row section"><view class="section-title">账单明细</view><button class="primary small" @click="go('expense',{id})">＋ 记一笔</button></view><view v-if="!expenses.length" class="empty">一顿好吃的，一张车票，都值得记下来。</view>
<view v-if="expenses.length" class="expense-list"><view v-for="e in expenses" :key="e.id" class="expense" @click="go('expense',{id,expense:e.id})"><view><view class="expense-title">{{e.title}}</view><view class="subtitle">{{e.category}} · {{names(e.payer)}}付款 · {{e.date.slice(5)}}</view></view><text class="expense-amount">¥{{yuan(e.amount)}} <text class="muted">›</text></text></view></view>
<view v-if="trip.settlements.length" class="section"><view class="section-title">结清记录</view><view v-for="s in trip.settlements" :key="s.id" class="row notice"><view>{{names(s.from)}} → {{names(s.to)}} ¥{{yuan(s.amount)}}<view class="subtitle">{{s.date}} · 不计入消费</view></view><button class="text-button small" @click="undo(s.id)">撤销</button></view></view>
<TripNav :id="id" :date="date" active="ledger"/><view class="footer-note">只记录花费，不发起支付</view></view></template>
<style scoped>.budget-card{background:#367be7;color:#ffffff;border-radius:24px;padding:25px}.budget-label{font-size:12px;opacity:.7}.budget-total{font-size:46px;font-family:inherit;margin:12px 0 22px}.budget-card .row{font-size:11px;opacity:.8}.progress{height:4px;background:#ffffff25;border-radius:10px;margin-top:14px;overflow:hidden}.progress view{height:100%;background:#a1ceff}.member-amount{font-size:24px;font-family:inherit;margin:5px 0}.net{font-size:12px;margin-top:10px;color:#5a7ca7}.expense{display:flex;justify-content:space-between;align-items:center;padding:17px 18px;margin-top:12px}.expense-title{font-size:15px;font-weight:600}.expense .subtitle{font-size:11px;margin-top:5px}.expense-amount{font-size:19px;font-family:inherit}</style>

<style scoped src="../../styles/ledger-ios.css"></style>
