<script setup lang="ts">
import {computed,ref,reactive} from 'vue';import {onLoad} from '@dcloudio/uni-app';import {initialize,findTrip,saveTrip,state,notify,confirm,canEditTrip} from '../../state';import {clone,uid} from '../../domain/types';import {parseCents,splitEqual} from '../../domain/money';
const id=ref(''),expenseId=ref('');const trip=computed(()=>findTrip(id.value));const categories=['交通','住宿','餐饮','门票','购物','其他'];const splitMode=ref('AA');const custom=reactive<Record<string,string>>({});const form=reactive({title:'',amount:'',category:'餐饮',date:'',payer:''});
onLoad(async q=>{id.value=q?.id||'';expenseId.value=q?.expense||'';await initialize();const t=trip.value;if(!t)return;form.date=t.startDate;form.payer=t.members[0].id;const e=t.expenses.find(e=>e.id===expenseId.value);if(e){Object.assign(form,{title:e.title,amount:String(e.amount/100),category:e.category,date:e.date,payer:e.payer});splitMode.value='自定义';t.members.forEach(m=>custom[m.id]=String((e.shares[m.id]||0)/100));}});
async function save(){if(!trip.value)return;try{const amount=parseCents(form.amount);const members=trip.value.members.map(m=>m.id);const shares=splitMode.value==='AA'?splitEqual(amount,members):splitMode.value==='自定义'?Object.fromEntries(members.map(m=>[m,parseCents(custom[m]||'0')])):Object.fromEntries(members.map(m=>[m,m===splitMode.value?amount:0]));const e={id:expenseId.value||uid(),title:form.title.trim(),amount,category:form.category,date:form.date,payer:form.payer,shares};const next=clone(trip.value);const i=next.expenses.findIndex(x=>x.id===e.id);if(i<0)next.expenses.push(e);else next.expenses[i]=e;await saveTrip(next);uni.navigateBack();}catch(e){notify(e);}}
async function remove(){if(!trip.value||!await confirm('删除这笔支出','删除后总花费和待结算金额会重新计算。'))return;try{const next=clone(trip.value);next.expenses=next.expenses.filter(e=>e.id!==expenseId.value);await saveTrip(next);uni.navigateBack();}catch(e){notify(e);}}
</script>
<template><view class="screen" v-if="trip"><text class="eyebrow">EVERY LITTLE MOMENT</text><view class="title">{{expenseId?'整理一笔花费':'今天，花在了哪里？'}}</view><text class="label">金额（元）</text><input class="field amount-input" type="digit" v-model="form.amount" placeholder="0.00"/><text class="label">记点什么</text><input class="field" v-model="form.title" maxlength="80" placeholder="例如：山脚下的晚餐"/>
<text class="label">分类</text><view class="pill-row"><text v-for="c in categories" :key="c" class="pill" :class="{active:form.category===c}" @click="form.category=c">{{c}}</text></view>
<text class="label">发生日期</text><picker mode="date" :value="form.date" @change="form.date=$event.detail.value"><view class="field field-text">{{form.date}}</view></picker>
<text class="label">谁支付了这笔钱</text><view class="pill-row"><text v-for="m in trip.members" :key="m.id" class="pill" :class="{active:form.payer===m.id}" @click="form.payer=m.id">{{m.name}}</text></view>
<text class="label">怎么分摊</text><view class="pill-row"><text class="pill" :class="{active:splitMode==='AA'}" @click="splitMode='AA'">AA 平摊</text><text v-for="m in trip.members" :key="m.id" class="pill" :class="{active:splitMode===m.id}" @click="splitMode=m.id">全算{{m.name}}的</text><text class="pill" :class="{active:splitMode==='自定义'}" @click="splitMode='自定义'">自定义</text></view>
<view v-if="splitMode==='自定义'" class="two-col"><view v-for="m in trip.members" :key="m.id"><text class="label">{{m.name}}承担（元）</text><input class="field" type="digit" v-model="custom[m.id]" placeholder="0.00"/></view></view>
<view class="notice">分摊总额必须等于支出金额。AA 的余分按成员顺序分配。修改已结算账单后，余额会重新计算。</view><button class="primary section" :loading="state.busy" :disabled="state.busy||!canEditTrip(id)||!state.ready" @click="save">保存这笔花费</button><button v-if="expenseId" class="danger section" :disabled="state.busy||!canEditTrip(id)||!state.ready" @click="remove">删除支出</button></view></template>
<style scoped>.amount-input{height:85px;font-size:38px;font-family:inherit}</style>

