import{existsSync,writeFileSync,mkdirSync}from'node:fs';import{randomBytes}from'node:crypto';import path from'node:path';import{createService}from'../server/service.ts';
const file=path.join(import.meta.dirname,'../data/demo.sqlite');mkdirSync(path.dirname(file),{recursive:true});if(existsSync(file)){console.log('示例工作区已存在，未覆盖。');process.exit()}
const s=createService(file);const password=randomBytes(12).toString('base64url');const a=s.createUser('旅行体验',password),t=s.createTrip(a.id,{title:'杭州 · 留一点时间给西湖',startDate:'2026-10-01',endDate:'2026-10-03',timeZone:'Asia/Shanghai'});const b=s.accept(s.invite(a.id,t.id,'editor').token,{username:'同行体验',password}).user;const partner=crypto.randomUUID();const put=(kind:string,data:any,id=crypto.randomUUID())=>{s.command(a.id,t.id,{type:'writeEntity',kind,id,mutationId:crypto.randomUUID(),expectedVersion:0,data});return id};put('participant',{name:'同行体验',userId:b.id},partner);const own=s.snapshot(a.id,t.id).entities.find(e=>e.kind==='participant')!.id;
for(const[name,time,lat,lng,note]of [['断桥残雪','09:00',30.2584,120.1495,'从湖边开始，给散步留一点时间。'],['孤山公园','10:30',30.2525,120.1359,'这一段不赶路，顺路看看湖景。'],['曲院风荷','14:00',30.2517,120.1244,'午后沿湖慢慢走，随时可以休息。'],['苏堤','16:00',30.2402,120.1314,'傍晚散步，结束后再决定晚餐。']] as const)put('item',{name,date:'2026-10-01',fixedTime:time,durationMinutes:60,note,place:{latitude:lat,longitude:lng,crs:'WGS84'},locationStatus:'unconfirmed',travelMode:'walking',completed:false});
put('item',{name:'灵隐寺（候选）',date:null,durationMinutes:120,note:'与同行人商量后再安排日期。',completed:false});
put('transport',{name:'出发交通 · 示例待确认',mode:'train',fromName:'出发城市',toName:'杭州',departure:null,arrival:null,status:'planned',bookingNo:'',note:'这是演示记录，不是真实车票。'});
put('stay',{name:'西湖附近住宿 · 示例',checkIn:'2026-10-01',checkOut:'2026-10-03',checkInTime:'14:00',checkOutTime:'12:00',status:'planned',amount:0,note:'演示住宿，尚未预订。'});
const packing=[['轻便外套','clothing',1,own,'wear',false],['舒适步行鞋','clothing',1,own,'wear',true],['身份证','documents',1,own,'pack',true],['洗漱包','toiletries',1,partner,'pack',false],['手机充电器','electronics',1,own,'pack',false],['充电宝','electronics',1,partner,'pack',true],['雨伞','essentials',1,null,'pack',false],['水杯','essentials',2,null,'pack',false],['纸巾','essentials',1,partner,'pack',false],['车载充电器','driving',1,null,'pack',false]];
for(const[name,category,quantity,participantId,carryMode,packed]of packing)put('packing',{name,category,quantity,participantId,carryMode,packed,note:'示例物品，可按实际需要修改'});
put('guide',{title:'留白也是一种安排',content:'这是一趟用于体验功能的示例旅行。可以试着拖动顺序、添加交通，再和另一个体验账号一起勾选物品。所有安排都可以修改，不代表实际预订。',category:'guide',sourceUrl:'',dates:['2026-10-01'],itemIds:[]});
writeFileSync(path.join(import.meta.dirname,'../data/demo-access.json'),JSON.stringify({username:a.username,companion:b.username,password,tripId:t.id},null,2),{mode:0o600});s.close();console.log('已创建独立合成示例；登录资料保存在 data/demo-access.json。');
