import{check,dates,type Kind,type Data}from'./model.ts';import{safeObject,validateEntity}from'./validation.ts';import{arrivalInstant}from'./domain.ts';
export interface ImportedTrip{title:string;startDate:string;endDate:string;timeZone:string;entities:{id:string;kind:Kind;data:Data}[];days:{date:string|null;itemIds:string[]}[];original:unknown}
export function backupWarnings(value:unknown,index:number):string[]{const trip=backupTrips(value)[index];check(trip,'请选择一趟旅行');const known=new Set(['id','tripId','title','startDate','endDate','timeZone','archived','version','revision','seq','schemaVersion','role','members','items','stays','transports','guides','expenses','settlements','packing','entities','days']);const labels:Record<string,string>={city:'城市',budget:'预算',dayCities:'每日城市',imports:'历史导入标记'};return Object.keys(trip).filter(k=>!known.has(k)).map(k=>`${labels[k]||k}（保留在原始资料中）`)}
export function backupTrips(value:any):any[]{safeObject(value);if(value.format==='xingjian-web-backup'&&value.schema===1)return[value.trip];check(value.format==='xingjian-backup'&&[1,2].includes(value.schema)&&Array.isArray(value.data?.trips),'不支持的备份格式');return value.data.trips}
export function normalizeBackup(value:unknown,index:number):ImportedTrip{
 const list=backupTrips(value);check(Number.isInteger(index)&&index>=0&&index<list.length,'请选择一趟旅行');const trip=list[index],web=(value as Data).format==='xingjian-web-backup';check(trip&&typeof trip.title==='string'&&trip.title.trim()&&trip.title.length<=120,'旅行名称无效');const range=dates(trip.startDate,trip.endDate),timeZone=web?trip.timeZone:'Asia/Shanghai';try{new Intl.DateTimeFormat('en',{timeZone}).format()}catch{throw Error('时区无效')}
 const source:{id:string;kind:Kind;data:Data}[]=web?trip.entities:[];if(!web){const map:Record<string,Kind>={members:'participant',items:'item',stays:'stay',transports:'transport',guides:'guide',expenses:'expense',settlements:'settlement',packing:'packing'};for(const[key,kind]of Object.entries(map)){check(trip[key]===undefined||Array.isArray(trip[key]),'备份列表格式无效');for(const d of trip[key]||[])source.push({id:d.id,kind,data:d})}}
 check(source.length<=3000,'单趟资料过多');const ids=new Map<string,string>(),kindById=new Map<string,Kind>();for(const e of source){check(typeof e.id==='string'&&e.id.length<=120&&!ids.has(e.id),'记录编号无效或重复');ids.set(e.id,crypto.randomUUID());kindById.set(e.id,e.kind)}
 const ref=(id:any,kind:Kind,optional=false)=>{if(optional&&!id)return null;check(ids.has(id)&&kindById.get(id)===kind,'关联记录不存在或类型不匹配');return ids.get(id)!};
 const zoneTime=(s:string)=>s?{local:s.slice(0,16),timeZone:'Asia/Shanghai',offset:'+08:00'}:null;
 const entities=source.map(e=>{let d:Data=JSON.parse(JSON.stringify(e.data));delete d.id;delete d.userId;if(!web){if(e.kind==='item')d={...d,durationMinutes:d.duration,fixedTime:d.time||null,place:d.place?{...d.place,crs:'GCJ02'}:null};if(e.kind==='transport')d={...d,departure:zoneTime(d.departure),arrival:zoneTime(d.arrival),status:d.bookingNo?'booked':'planned'};if(e.kind==='packing')d={...d,participantId:d.memberId||null,carryMode:d.carryMode||'pack'}}
 if(e.kind==='item')check(d.date===null||range.includes(d.date),'事项日期超出旅行');if(e.kind==='packing')d.participantId=ref(d.participantId,'participant',true);if(e.kind==='guide')d.itemIds=(d.itemIds||[]).map((id:string)=>ref(id,'item'));if(e.kind==='transport'){d.fromItemId=ref(d.fromItemId,'item',true);d.toItemId=ref(d.toItemId,'item',true);if(d.departure)arrivalInstant(d.departure);if(d.arrival)arrivalInstant(d.arrival);check(!d.departure||!d.arrival||arrivalInstant(d.arrival)>=arrivalInstant(d.departure),'到达不能早于出发')}
 if(e.kind==='expense'){d.payer=ref(d.payer,'participant');d.shares=Object.fromEntries(Object.entries(d.shares||{}).map(([id,n])=>[ref(id,'participant'),n]))}if(e.kind==='settlement'){d.from=ref(d.from,'participant');d.to=ref(d.to,'participant')}
 return{id:ids.get(e.id)!,kind:e.kind,data:validateEntity(e.kind,d)}});
 const days=[null,...range].map(date=>({date,itemIds:[]as string[]}));if(web){const seen=new Set<string>();for(const d of trip.days||[]){const dest=days.find(x=>x.date===d.date);check(dest,'日程日期无效');for(const id of d.itemIds){const item=source.find(e=>e.id===id&&e.kind==='item');check(item&&item.data.date===d.date&&!seen.has(id),'日程顺序不一致');seen.add(id);dest.itemIds.push(ref(id,'item')!)}}check(source.filter(e=>e.kind==='item').every(e=>seen.has(e.id)),'日程缺少事项')}else{for(const e of source.filter(e=>e.kind==='item').sort((a,b)=>(a.data.order||0)-(b.data.order||0)))days.find(d=>d.date===e.data.date)!.itemIds.push(ref(e.id,'item')!)}
 let original:unknown=trip;
 if(web&&(value as Data).legacyPayload!==undefined){const raw=(value as Data).legacyPayload;try{original=typeof raw==='string'?JSON.parse(raw):raw;safeObject(original)}catch{throw Error('原始备份资料无效')}}
 return{title:trip.title,startDate:trip.startDate,endDate:trip.endDate,timeZone,entities,days,original};
}

