import transform from 'coordtransform';
import {check,dateValid,type Data,type Point} from './model.ts';
export const toMapPoint=(p:Point):Point=>{if(p.crs==='WGS84')return{...p};const[longitude,latitude]=transform.gcj02towgs84(p.longitude,p.latitude);return{latitude,longitude,crs:'WGS84'}};
export function parseCents(t:string){check(/^\d+(\.\d{1,2})?$/.test(t.trim()),'金额最多两位小数');const[a,b='']=t.trim().split('.');const n=Number(a)*100+Number(b.padEnd(2,'0'));check(Number.isSafeInteger(n)&&n<=100000000,'金额超出范围');return n}
export function splitEqual(amount:number,ids:string[]){check(Number.isSafeInteger(amount)&&amount>=0&&ids.length>0&&new Set(ids).size===ids.length,'分摊无效');return Object.fromEntries(ids.map((id,i)=>[id,Math.floor(amount/ids.length)+(i<amount%ids.length?1:0)]))}
export function balances(expenses:Data[],settlements:Data[]){const result:Record<string,number>={};const add=(id:string,n:number)=>result[id]=(result[id]||0)+n;for(const e of expenses){add(e.payer,e.amount);for(const[id,n]of Object.entries(e.shares))add(id,-Number(n))}for(const s of settlements){add(s.from,s.amount);add(s.to,-s.amount)}return result}
export interface ZonedTime{local:string;timeZone:string;offset:string}
export function arrivalInstant(t:ZonedTime){check(t&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(t.local)&&/^[+-](?:0\d|1[0-4]):[0-5]\d$/.test(t.offset),'请填写日期、当地时间、时区和 UTC 偏移');const n=Date.parse(t.local+t.offset);check(Number.isFinite(n),'交通时间无效');let parts:Intl.DateTimeFormatPart[];try{parts=new Intl.DateTimeFormat('en-CA',{timeZone:t.timeZone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(n)}catch{throw Error('时区无效')}const p=Object.fromEntries(parts.map(x=>[x.type,x.value]));check(`${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}`===t.local,'当地时间与时区偏移不一致（请检查夏令时）');return n}
export function dateInZone(n:number,zone:string){const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(n).map(x=>[x.type,x.value]));return`${p.year}-${p.month}-${p.day}`}
export function travelForDay(date:string,zone:string,transports:Data[],stays:Data[]){const result:{type:string;name:string;time:string;note?:string}[]=[];for(const t of transports)for(const[field,type]of [['departure','出发'],['arrival','到达']])if(t[field]&&dateInZone(arrivalInstant(t[field]),zone)===date)result.push({type,name:t.name,time:t[field].local.replace('T',' '),note:`${t.fromName||''} → ${t.toName||''}`});for(const s of stays){if(s.checkIn===date)result.push({type:'入住',name:s.name,time:s.checkInTime||'时间待核对'});else if(s.checkIn<date&&s.checkOut>date)result.push({type:'住宿',name:s.name,time:'今晚'});if(s.checkOut===date)result.push({type:'退房',name:s.name,time:s.checkOutTime||'时间待核对'})}return result}
export function planTimes(items:Data[],legs:Data[]){const rows:Data[]=[];for(const [i,item]of items.entries()){const prev=rows[i-1];const leg=legs.find(l=>l.from===items[i-1]?.id&&l.to===item.id);const travel=typeof leg?.durationSeconds==='number'&&Number.isFinite(leg.durationSeconds)&&leg.durationSeconds>=0?Math.ceil(leg.durationSeconds/60):undefined;const fixed=item.fixedTime?Number(item.fixedTime.slice(0,2))*60+Number(item.fixedTime.slice(3)):undefined;const arrival=prev?.end!==undefined&&travel!==undefined?prev.end+travel:undefined;const start=fixed??arrival;rows.push({id:item.id,start,end:start===undefined?undefined:start+item.durationMinutes,conflictMinutes:fixed!==undefined&&arrival!==undefined?Math.max(0,arrival-fixed):0,trafficUnknown:i>0&&travel===undefined})}return rows}
export function scheduleLegs(items:Data[],routes:{from:string;to:string;result:Partial<LegResult>}[]):Data[]{return items.slice(0,-1).flatMap((item,i)=>{const found=routes.find(r=>r.from===item.id&&r.to===items[i+1].id)?.result;const manual=typeof item.manualTravelMinutes==='number'&&Number.isFinite(item.manualTravelMinutes)&&item.manualTravelMinutes>=0;const durationSeconds=manual?item.manualTravelMinutes*60:found?.status==='ready'?found.durationSeconds:undefined;return durationSeconds===undefined?[]:[{from:item.id,to:items[i+1].id,durationSeconds,source:manual?'manual':'route'}]})}
export function mergePackingTemplate(existing:Data[],incoming:Data[]){const key=(p:Data)=>JSON.stringify([p.name.trim(),p.category,p.participantId,p.carryMode]);const found=new Set(existing.map(key));const result=[...existing];for(const p of incoming)if(!found.has(key(p))){found.add(key(p));result.push(p)}return result}
export function suggestClothes(days:number,washEveryDays:number,participantId:string):Data[]{check(Number.isInteger(days)&&days>=1&&days<=366&&Number.isInteger(washEveryDays)&&washEveryDays>=1,'天数无效');const n=Math.min(days,washEveryDays);return[['袜子',n],['内衣',n],['上衣',Math.max(1,Math.ceil(n/2))],['长裤',Math.max(1,Math.ceil(n/3))]].flatMap(([name,count])=>[{name,category:'clothing',quantity:1,participantId,packed:false,carryMode:'wear',note:'出发当天穿着'},...(Number(count)>1?[{name,category:'clothing',quantity:Number(count)-1,participantId,packed:false,carryMode:'pack',note:'按洗换间隔估算，可编辑'}]:[])])}
export interface LegResult{status:'ready'|'unconfigured'|'unsupported'|'unlocated'|'failed';distanceMeters?:number;durationSeconds?:number;geometry?:Point[];provider?:string;queriedAt?:string;message?:string}
export function parseOsrm(v:any):LegResult{const r=v?.routes?.[0];if(v?.code!=='Ok'||!r||!Number.isFinite(r.distance)||r.distance<0||!Number.isFinite(r.duration)||r.duration<0||r.geometry?.type!=='LineString'||!Array.isArray(r.geometry.coordinates)||r.geometry.coordinates.length<2||r.geometry.coordinates.length>50000||r.geometry.coordinates.some((p:any)=>!Array.isArray(p)||!Number.isFinite(p[0])||Math.abs(p[0])>180||!Number.isFinite(p[1])||Math.abs(p[1])>90))return{status:'failed',message:'未取得有效道路路线'};return{status:'ready',distanceMeters:r.distance,durationSeconds:r.duration,geometry:r.geometry.coordinates.map(([longitude,latitude]:number[])=>({latitude,longitude,crs:'WGS84'})),provider:'OSRM',queriedAt:new Date().toISOString()}}
export function forecastWindow(date:string,today:string){if(!dateValid(date)||!dateValid(today))return false;const n=(Date.parse(date)-Date.parse(today))/86400000;return n>=0&&n<16}
