<script setup lang="ts">
import {computed,ref,watch} from 'vue';
import type {Place} from '../domain/types';
import {today} from '../domain/dates';
import {forecastRange,weatherPreparation,type DailyForecast} from '../domain/weather';
import {fetchWeather} from '../services/weather';
const props=defineProps<{date:string;places:Place[]}>();
const opened=ref(false),busy=ref(false),error=ref(''),index=ref(0),result=ref<DailyForecast>(),updated=ref('');let request=0;
const place=computed(()=>props.places[index.value]);
const range=computed(()=>props.date?forecastRange(props.date,today()):'future');
const tips=computed(()=>result.value?weatherPreparation(result.value):[]);
watch(()=>[props.date,place.value?.id,place.value?.latitude,place.value?.longitude],()=>{request++;busy.value=false;result.value=undefined;error.value='';updated.value='';});
watch(()=>props.places,()=>{if(index.value>=props.places.length)index.value=0;});
async function query(){if(!place.value||busy.value)return;const token=++request;busy.value=true;error.value='';try{const data=await fetchWeather(place.value,props.date);if(token!==request)return;result.value=data.forecast;updated.value=new Date(data.updatedAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'});if(!data.forecast)error.value='暂时没有这一天的预报，请临近出发再查';}catch(e){if(token===request)error.value=e instanceof Error?e.message:'天气暂不可用';}finally{if(token===request)busy.value=false;}}
</script>
<template><view class="weather-card"><button class="weather-toggle" @click="opened=!opened"><view class="weather-dot"/><view class="weather-heading"><text>当地天气与穿衣</text><text class="weather-sub">{{result?`${result.description} · ${result.low??'—'}～${result.high??'—'}°C`:range==='future'?'临近出发再看预报':range==='past'?'当前仅支持未来天气预报':'按行程地点查看'}}</text></view><text>{{opened?'收起':'查看'}}</text></button>
<view v-if="opened" class="weather-content"><view v-if="range!=='available'" class="weather-hint">{{range==='future'?'尚未进入16天预报范围，不用季节平均值代替具体预报。':'行程日期已过去，此入口不提供历史天气。'}}</view><template v-else><picker v-if="places.length" :range="places.map(p=>p.name)" :value="index" @change="index=Number($event.detail.value)"><view class="weather-location">{{place?.name}}附近 · {{date.slice(5)}} ▾</view></picker><view v-else class="weather-hint">这一天还没有保存位置，可先在地图里给当天地点选点。</view><button v-if="place" class="secondary small" :loading="busy" :disabled="busy" @click="query">{{result?'刷新预报':'查询天气'}}</button><view v-if="error" class="weather-hint">{{error}}</view><view v-if="result" class="weather-result"><view>{{result.description}} · {{result.low??'—'}}～{{result.high??'—'}}°C</view><view class="weather-hint">降水概率 {{result.rain===undefined?'暂无':result.rain+'%'}} · 最大风速 {{result.wind===undefined?'暂无':result.wind+' km/h'}}</view><view v-for="tip in tips" :key="tip" class="weather-tip">{{tip}}</view><view class="weather-hint">按所选地点附近预报，不代表整段跨城路线；建议仅供准备时参考。</view></view></template><view class="weather-source">Open-Meteo · CC BY 4.0{{updated?' · '+updated+' 获取':''}}<view>点击查询才联网；不会自动改动衣物清单。</view></view></view></view></template>
<style scoped>.weather-card{border:1px solid var(--line);border-radius:16px;background:var(--surface);overflow:hidden}.weather-toggle{display:flex;align-items:center;gap:10px;width:100%;padding:12px 14px;text-align:left;background:transparent;border-radius:0;font-size:13px;color:var(--ink)}.weather-dot{width:18px;height:18px;border:2px solid #edac35;border-radius:50%;box-shadow:0 0 0 4px #fff3d9;flex-shrink:0}.weather-heading{flex:1;min-width:0;display:flex;flex-direction:column;gap:3px}.weather-sub{font-size:12px;color:var(--ink-muted);font-weight:400}.weather-toggle>text{color:var(--brand);font-size:12px;flex-shrink:0}.weather-content{padding:0 14px 14px}.weather-hint,.weather-source{font-size:12px;line-height:1.7;color:var(--ink-muted);margin-top:8px}.weather-source{font-size:11px;border-top:1px solid var(--line);padding-top:8px}.weather-location{padding:10px 0;font-size:13px;color:var(--brand);overflow-wrap:anywhere}.weather-result{font-size:18px;margin-top:14px;font-weight:600}.weather-tip{font-size:12px;font-weight:400;background:var(--surface-muted);border-radius:8px;padding:8px;margin-top:6px}</style>
