<script setup lang="ts">
import {cloneDraft} from "../../../shared/drafts";
import{ref,computed,watch}from'vue';import Modal from'../ui/Modal.vue';import{categories,modes,type Kind,type Entity,type Data,type Snapshot}from'../../../shared/model';import{parseCents,splitEqual}from'../../../shared/domain';
const props=defineProps<{userId:string;draftId:string;kind:Kind;entity:Entity|null;snapshot:Snapshot;date:string|null;error:string;busy:boolean;remoteChanged:boolean}>();const emit=defineEmits<{save:[data:Data,baseVersion:number,draftId:string];close:[]}>();const participants=computed(()=>props.snapshot.entities.filter(e=>e.kind==='participant'));const titles:Record<Kind,string>={item:'事项',packing:'物品',transport:'交通',stay:'住宿',guide:'攻略',expense:'支出',settlement:'结清',participant:'参与者'};
const defaults:Record<Kind,Data>={item:{name:'',date:props.date,fixedTime:null,durationMinutes:60,note:'',place:null,locationStatus:'unconfirmed',completed:false,travelMode:'driving'},packing:{name:'',category:'clothing',quantity:1,participantId:null,packed:false,carryMode:'pack',note:''},transport:{name:'',mode:'train',fromName:'',toName:'',departure:null,arrival:null,fromItemId:null,toItemId:null,bookingNo:'',status:'planned',note:''},stay:{name:'',checkIn:props.date||props.snapshot.startDate,checkOut:props.snapshot.endDate,checkInTime:'14:00',checkOutTime:'12:00',status:'planned',address:'',bookingNo:'',note:'',amount:0},guide:{title:'',content:'',sourceUrl:'',sourceText:'',dates:[],itemIds:[],category:'guide',note:''},expense:{title:'',amount:0,date:props.date||props.snapshot.startDate,payer:participants.value[0]?.id||'',shares:{},category:'餐饮',note:''},settlement:{from:participants.value[0]?.id||'',to:participants.value[1]?.id||'',amount:0,date:props.date||props.snapshot.startDate,note:''},participant:{name:'',note:''}};
const form=ref<Data>(cloneDraft(props.entity?.data||defaults[props.kind]));const lat=ref(form.value.place?.latitude??''),lng=ref(form.value.place?.longitude??''),crs=ref(form.value.place?.crs||'WGS84');const amount=ref(String((form.value.amount||0)/100));const splitIds=ref<string[]>(Object.keys(form.value.shares||{}).length?Object.keys(form.value.shares):participants.value.map(e=>e.id));const customShares=ref(props.kind==='expense'&&!!props.entity),shares=ref<Record<string,string>>(Object.fromEntries(participants.value.map(e=>[e.id,String((form.value.shares?.[e.id]||0)/100)])));const localError=ref('');const depart=ref(form.value.departure?.local||''),arrive=ref(form.value.arrival?.local||''),departZone=ref(form.value.departure?.timeZone||props.snapshot.timeZone),arriveZone=ref(form.value.arrival?.timeZone||props.snapshot.timeZone),departOffset=ref(form.value.departure?.offset||'+08:00'),arriveOffset=ref(form.value.arrival?.offset||'+08:00');
const draftKey='xj-draft:'+props.userId+':'+props.snapshot.tripId+':'+props.kind+':'+(props.entity?.id||'new');
const baseVersion=ref(props.entity?.version||0), stableId=ref(props.draftId);
const fields={form,lat,lng,crs,amount,splitIds,customShares,shares,depart,arrive,departZone,arriveZone,departOffset,arriveOffset,baseVersion,stableId};
try{const saved=JSON.parse(sessionStorage.getItem(draftKey)||'null');if(saved)for(const [key,value]of Object.entries(fields)){if(key in saved)value.value=saved[key]}}catch{sessionStorage.removeItem(draftKey)}
watch(()=>Object.fromEntries(Object.entries(fields).map(([k,v])=>[k,v.value])),value=>{try{sessionStorage.setItem(draftKey,JSON.stringify(value))}catch{}},{deep:true});
watch(()=>props.entity?.version,value=>{if(value!==undefined)baseVersion.value=value});
function submit(){localError.value='';try{const data=cloneDraft(form.value);if(props.kind==='item'){if(lat.value!==''||lng.value!==''){if(lat.value===''||lng.value==='')throw Error('请同时填写经纬度');data.place={latitude:Number(lat.value),longitude:Number(lng.value),crs:crs.value}}else data.place=null;data.fixedTime=data.fixedTime||null}if(['expense','settlement','stay'].includes(props.kind))data.amount=parseCents(amount.value||'0');if(props.kind==='expense')data.shares=customShares.value?Object.fromEntries(splitIds.value.map(id=>[id,parseCents(shares.value[id]||'0')])):splitEqual(data.amount,splitIds.value);if(props.kind==='transport'){data.departure=depart.value?{local:depart.value,timeZone:departZone.value,offset:departOffset.value}:null;data.arrival=arrive.value?{local:arrive.value,timeZone:arriveZone.value,offset:arriveOffset.value}:null}emit('save',data,baseVersion.value,stableId.value)}catch(e){localError.value=(e as Error).message}}
</script>
<template><Modal :title="(entity?'编辑':'添加')+titles[kind]" @close="emit('close')"><form class="editor-form" @submit.prevent="submit"><p v-if="remoteChanged" class="notice">同行人更新了此项。你的草稿已保留，保存时会核对版本。</p><label v-if="!['guide','expense','settlement'].includes(kind)">名称<input v-model="form.name" required maxlength="120" autofocus></label><label v-if="['guide','expense'].includes(kind)">标题<input v-model="form.title" required maxlength="120" autofocus></label>
<template v-if="kind==='item'"><div class="form-grid"><label>安排日期<select v-model="form.date"><option :value="null">待规划</option><option v-for="day in snapshot.days.filter(d=>d.date)" :key="day.date!" :value="day.date">{{day.date}}</option></select></label><label>固定时间<input v-model="form.fixedTime" type="time"></label><label>停留分钟<input v-model.number="form.durationMinutes" type="number" min="0" max="10080" required></label><label>前往下一站<select v-model="form.travelMode"><option v-for="m in modes" :value="m[0]">{{m[1]}}</option></select></label></div><details><summary>位置与路段信息</summary><div class="form-grid"><label>纬度<input v-model="lat" type="number" step="any" min="-90" max="90"></label><label>经度<input v-model="lng" type="number" step="any" min="-180" max="180"></label></div><label>坐标来源<select v-model="crs"><option value="WGS84">地图选点 / GPS（WGS84）</option><option value="GCJ02">高德 / 腾讯（GCJ02）</option></select></label><label>位置状态<select v-model="form.locationStatus"><option value="unconfirmed">入口待核对</option><option value="confirmed">位置已确认</option><option value="not-needed">无需定位</option></select></label><label>手工预计交通分钟<input v-model.number="form.manualTravelMinutes" type="number" min="0" max="10080" placeholder="可不填，未知不推算"></label></details></template>
<template v-if="kind==='packing'"><div class="form-grid"><label>分类<select v-model="form.category"><option v-for="c in categories" :value="c[0]">{{c[1]}}</option></select></label><label>数量<input v-model.number="form.quantity" type="number" min="1" max="999" required></label></div><label>由谁准备<select v-model="form.participantId"><option :value="null">公共物品 / 未分配</option><option v-for="p in participants" :value="p.id">{{p.data.name}}</option></select></label><label>携带方式<select v-model="form.carryMode"><option value="pack">装进行李</option><option value="wear">出发时穿</option></select></label></template>
<template v-if="kind==='transport'"><div class="form-grid"><label>方式<select v-model="form.mode"><option v-for="m in modes" :value="m[0]">{{m[1]}}</option></select></label><label>状态<select v-model="form.status"><option value="planned">计划中</option><option value="booked">已预订</option></select></label><label>出发地点<input v-model="form.fromName" required></label><label>到达地点<input v-model="form.toName" required></label></div><label>出发日期与当地时间<input v-model="depart" type="datetime-local"></label><div class="form-grid"><label>出发时区<input v-model="departZone" placeholder="Asia/Shanghai"></label><label>出发 UTC 偏移<input v-model="departOffset" placeholder="+08:00"></label></div><label>到达日期与当地时间<input v-model="arrive" type="datetime-local"></label><div class="form-grid"><label>到达时区<input v-model="arriveZone"></label><label>到达 UTC 偏移<input v-model="arriveOffset"></label></div><div class="form-grid"><label>关联出发事项<select v-model="form.fromItemId"><option :value="null">无关联</option><option v-for="p in snapshot.entities.filter(e=>e.kind==='item')" :value="p.id">{{p.data.name}}</option></select></label><label>关联到达事项<select v-model="form.toItemId"><option :value="null">无关联</option><option v-for="p in snapshot.entities.filter(e=>e.kind==='item')" :value="p.id">{{p.data.name}}</option></select></label></div><label>班次 / 订单号<input v-model="form.bookingNo" maxlength="120"></label><p class="muted small">时间可留空；跨夜请填写实际到达日期。这里的预订不会自动计入账本。</p></template>
<template v-if="kind==='stay'"><div class="form-grid"><label>入住日期<input v-model="form.checkIn" type="date" required></label><label>退房日期<input v-model="form.checkOut" type="date" required></label><label>入住时间<input v-model="form.checkInTime" type="time"></label><label>退房时间<input v-model="form.checkOutTime" type="time"></label></div><label>地址<input v-model="form.address"></label><label>状态<select v-model="form.status"><option value="planned">计划中</option><option value="booked">已预订</option></select></label><label>订单号<input v-model="form.bookingNo"></label><label>订单金额（元）<input v-model="amount" inputmode="decimal"></label></template>
<template v-if="kind==='guide'"><label>分类<select v-model="form.category"><option value="guide">游玩攻略</option><option value="transport">交通提醒</option><option value="checklist">出行备忘</option></select></label><label>正文<textarea v-model="form.content" rows="6" maxlength="12000"></textarea></label><label>来源链接<input v-model="form.sourceUrl" type="url" placeholder="https://"></label><label>分享原文<textarea v-model="form.sourceText" rows="2" maxlength="4000"></textarea></label><fieldset><legend>关联日期</legend><label class="check-label" v-for="d in snapshot.days.filter(d=>d.date)"><input v-model="form.dates" type="checkbox" :value="d.date">{{d.date}}</label></fieldset><label>关联事项<select v-model="form.itemIds" multiple size="4"><option v-for="i in snapshot.entities.filter(e=>e.kind==='item')" :value="i.id">{{i.data.name}}</option></select></label></template>
<template v-if="kind==='expense'"><div class="form-grid"><label>金额（元）<input v-model="amount" inputmode="decimal" required></label><label>日期<input v-model="form.date" type="date" required></label><label>付款人<select v-model="form.payer"><option v-for="p in participants" :value="p.id">{{p.data.name}}</option></select></label><label>分类<select v-model="form.category"><option v-for="c in ['餐饮','交通','住宿','门票','购物','其他']">{{c}}</option></select></label></div><fieldset><legend>分摊成员</legend><label class="check-label" v-for="p in participants"><input v-model="splitIds" type="checkbox" :value="p.id">{{p.data.name}}<input v-if="customShares&&splitIds.includes(p.id)" v-model="shares[p.id]" inputmode="decimal" :aria-label="p.data.name+'分摊金额'"></label></fieldset><label class="check-label"><input v-model="customShares" type="checkbox">指定每人金额（默认均分）</label></template>
<template v-if="kind==='settlement'"><div class="form-grid"><label>转出人<select v-model="form.from"><option v-for="p in participants" :value="p.id">{{p.data.name}}</option></select></label><label>收款人<select v-model="form.to"><option v-for="p in participants" :value="p.id">{{p.data.name}}</option></select></label><label>金额（元）<input v-model="amount" inputmode="decimal" required></label><label>日期<input v-model="form.date" type="date" required></label></div></template>
<label v-if="kind!=='guide'">备注<textarea v-model="form.note" rows="3" maxlength="2000" placeholder="留给自己，也留给同行人"></textarea></label><p v-if="error||localError" class="error" role="alert">{{error||localError}}</p><footer class="form-footer"><button type="button" class="secondary" @click="emit('close')">取消</button><button class="primary" :disabled="busy">{{busy?'正在保存…':'保存'+titles[kind]}}</button></footer></form></Modal></template>



