<script setup lang="ts">
import{ref,onMounted,onUnmounted,watch}from'vue';import L from'leaflet';import'leaflet/dist/leaflet.css';import{toMapPoint,type LegResult}from'../../../shared/domain';import type{Entity}from'../../../shared/model';
const props=defineProps<{items:Entity[];selected:string|null;routes:{from:string;to:string;result:LegResult}[];picking:boolean}>();const emit=defineEmits<{select:[id:string];pick:[lat:number,lng:number]}>();const host=ref<HTMLElement>();const failed=ref(false);let map:L.Map,group:L.LayerGroup,tile:L.TileLayer,observer:ResizeObserver;let signature='';
function draw(){if(!map)return;group.clearLayers();const located=props.items.filter(e=>e.data.place);for(const e of located){const p=toMapPoint(e.data.place);const n=props.items.findIndex(i=>i.id===e.id)+1;const tooltip=document.createElement('span');tooltip.textContent=e.data.name;L.marker([p.latitude,p.longitude],{icon:L.divIcon({className:'',html:`<span class="map-pin ${props.selected===e.id?'active':''}">${n}</span>`,iconSize:[32,40],iconAnchor:[16,40]})}).bindTooltip(tooltip,{direction:'top',offset:[0,-38]}).on('click',()=>emit('select',e.id)).addTo(group)}for(let i=0;i<props.items.length-1;i++){const a=props.items[i],b=props.items[i+1];if(!a.data.place||!b.data.place)continue;const result=props.routes.find(r=>r.from===a.id&&r.to===b.id)?.result;const ps=result?.status==='ready'?result.geometry!.map(p=>[p.latitude,p.longitude] as L.LatLngTuple):[a,b].map(e=>{const p=toMapPoint(e.data.place);return[p.latitude,p.longitude]as L.LatLngTuple});L.polyline(ps,{color:result?.status==='ready'?'#1877ef':'#6688ad',weight:result?.status==='ready'?4:2,dashArray:result?.status==='ready'?undefined:'5 8',opacity:.8}).addTo(group)}const next=located.map(e=>`${e.id}:${JSON.stringify(e.data.place)}`).join('|');if(next!==signature){signature=next;fit()}}
function fit(){const ps=props.items.filter(e=>e.data.place).map(e=>{const p=toMapPoint(e.data.place);return[p.latitude,p.longitude]as L.LatLngTuple});if(ps.length)map.fitBounds(L.latLngBounds(ps),{padding:[60,70],maxZoom:15,animate:!matchMedia('(prefers-reduced-motion: reduce)').matches})}
onMounted(()=>{map=L.map(host.value!,{zoomControl:false}).setView([30.25,120.14],12);L.control.zoom({position:'bottomright'}).addTo(map);tile=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',maxZoom:19}).addTo(map);tile.on('tileerror',()=>failed.value=true);group=L.layerGroup().addTo(map);map.on('click',(e:L.LeafletMouseEvent)=>{if(props.picking)emit('pick',Number(e.latlng.lat.toFixed(6)),Number(e.latlng.lng.toFixed(6)))});observer=new ResizeObserver(()=>map.invalidateSize());observer.observe(host.value!);draw()});watch(()=>[props.items,props.selected,props.routes],draw,{deep:true});watch(()=>props.selected,id=>{const e=props.items.find(e=>e.id===id);if(map&&e?.data.place){const p=toMapPoint(e.data.place);map.setView([p.latitude,p.longitude],Math.max(map.getZoom(),14),{animate:!matchMedia('(prefers-reduced-motion: reduce)').matches})}});onUnmounted(()=>{observer?.disconnect();map?.remove()});
</script>
<template><div class="map-container"><div ref="host" class="map-surface" aria-label="旅行地点地图"></div><div class="map-top"><span class="map-badge"><span class="live-dot"></span>{{items.filter(e=>e.data.place).length}} 个已定位地点</span><button class="map-badge" @click="fit">查看全程</button></div><div v-if="picking" class="map-hint">在地图上点选位置，然后确认保存</div><div v-if="failed" class="map-error">底图暂不可用，仍可编辑行程 <button @click="failed=false;tile.redraw()">重试</button></div><div class="map-legend"><i></i> 虚线为游览顺序，不代表道路路线</div></div></template>

