import {it,expect} from 'vitest';
import {createService} from '../server/service.ts';
const password='test-password-123';
function setup(){const s=createService(':memory:');const a=s.createUser('alice',password);const t=s.createTrip(a.id,{title:'湖畔周末',startDate:'2026-10-01',endDate:'2026-10-03',timeZone:'Asia/Shanghai'});return{s,a,t}}
it('redeems invite once and separates ledger participants from accounts',()=>{const{s,a,t}=setup();try{const inv=s.invite(a.id,t.id,'editor');const b=s.accept(inv.token,{username:'bob',password});expect(s.snapshot(b.user.id,t.id).role).toBe('editor');expect(()=>s.accept(inv.token,{username:'carol',password})).toThrow();expect(s.db.get('SELECT count(*) n FROM users')).toMatchObject({n:2});}finally{s.close()}});
it('enforces access, CAS conflict and mutation idempotency',()=>{const{s,a,t}=setup();try{const b=s.createUser('bob',password);expect(()=>s.snapshot(b.id,t.id)).toThrow();const c={type:'writeEntity',kind:'item',id:crypto.randomUUID(),mutationId:crypto.randomUUID(),expectedVersion:0,data:{name:'公园',date:'2026-10-01',durationMinutes:60,note:'',completed:false}};s.command(a.id,t.id,c);s.command(a.id,t.id,c);expect(s.snapshot(a.id,t.id).entities.filter(e=>e.kind==='item')).toHaveLength(1);expect(()=>s.command(a.id,t.id,{...c,mutationId:crypto.randomUUID()})).toThrow(/更新/);expect(()=>s.command(a.id,t.id,{...c,data:{...c.data,name:'changed'}})).toThrow(/重复/);}finally{s.close()}});
it('revokes member editing without deleting assigned packing',()=>{const{s,a,t}=setup();try{const b=s.accept(s.invite(a.id,t.id,'editor').token,{username:'bob',password}).user;const id=crypto.randomUUID();s.command(b.id,t.id,{type:'writeEntity',kind:'packing',id,mutationId:crypto.randomUUID(),expectedVersion:0,data:{name:'雨衣',category:'clothing',quantity:1,participantId:null,packed:false,carryMode:'pack',note:''}});s.removeMember(a.id,t.id,b.id);expect(()=>s.command(b.id,t.id,{type:'deleteEntity',kind:'packing',id,mutationId:crypto.randomUUID(),expectedVersion:1})).toThrow();expect(s.snapshot(a.id,t.id).entities.find(e=>e.id===id)).toBeTruthy();}finally{s.close()}});
it('does not allow deleting the last owner or using viewer to write',()=>{const{s,a,t}=setup();try{expect(()=>s.removeMember(a.id,t.id,a.id)).toThrow();const b=s.accept(s.invite(a.id,t.id,'viewer').token,{username:'bob',password}).user;expect(()=>s.command(b.id,t.id,{type:'writeEntity',kind:'item',id:crypto.randomUUID(),mutationId:crypto.randomUUID(),expectedVersion:0,data:{name:'test'}})).toThrow();}finally{s.close()}});
it('moves an item atomically with day versions and rejects stale reorder',()=>{const{s,a,t}=setup();try{const id=crypto.randomUUID();s.command(a.id,t.id,{type:'writeEntity',kind:'item',id,mutationId:crypto.randomUUID(),expectedVersion:0,data:{name:'公园',date:'2026-10-01'}});const snap=s.snapshot(a.id,t.id);const from=snap.days.find(d=>d.date==='2026-10-01')!;const to=snap.days.find(d=>d.date==='2026-10-02')!;const cmd={type:'moveItem',id,date:to.date,beforeId:null,expectedVersion:1,fromDayVersion:from.version,toDayVersion:to.version,mutationId:crypto.randomUUID()};s.command(a.id,t.id,cmd);expect(s.snapshot(a.id,t.id).days.find(d=>d.date===to.date)?.itemIds).toEqual([id]);expect(()=>s.command(a.id,t.id,{...cmd,mutationId:crypto.randomUUID()})).toThrow();}finally{s.close()}});
