import {randomUUID} from 'node:crypto';
import {EventEmitter} from 'node:events';
import {openDb} from './db.ts';
import {digest,token,passwordHash,passwordMatches,username} from './auth.ts';
import {check,AppError,dates,type Role,type Entity,type Snapshot,type Data,type Kind} from '../shared/model.ts';
import {validateEntity} from '../shared/validation.ts';
const entity=(r:any):Entity=>({id:r.id,tripId:r.trip_id,kind:r.kind,data:JSON.parse(r.data),version:r.version,updatedAt:r.updated_at,updatedBy:r.updated_by});
export function createService(filename:string){
 const db=openDb(filename),events=new EventEmitter();events.setMaxListeners(1000);
 function createUser(name:string,password:string){const normalized=username(name);check(!db.get('SELECT id FROM users WHERE username=?',normalized),'用户名已被使用',409);const u={id:randomUUID(),username:normalized};db.run('INSERT INTO users VALUES(?,?,?)',u.id,u.username,passwordHash(password));return u}
 function login(name:string,password:string){const u=db.get('SELECT * FROM users WHERE username=?',username(name));check(u&&passwordMatches(password,u.password_hash),'用户名或密码不正确',401);const session=token();db.run('INSERT INTO sessions VALUES(?,?,?)',digest(session),u.id,Date.now()+7*86400000);return{token:session,user:{id:u.id,username:u.username}}}
 function session(value:string){return db.get('SELECT u.id,u.username FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.hash=? AND s.expires>?',digest(value),Date.now())}
 function access(userId:string,tripId:string,mode:'read'|'write'|'manage'='read'):Role{const m=db.get('SELECT role FROM memberships WHERE user_id=? AND trip_id=?',userId,tripId);check(m,'你没有这趟旅行的访问权限',403);check(mode==='read'||mode==='write'&&m.role!=='viewer'||m.role==='owner','当前账号没有操作权限',403);return m.role}
 function tripMeta(input:Data){const range=dates(input.startDate,input.endDate);check(typeof input.title==='string'&&input.title.trim()&&input.title.length<=120,'请输入旅行名称');try{new Intl.DateTimeFormat('en',{timeZone:input.timeZone}).format()}catch{throw new AppError('时区无效')}return range}
 function createTrip(userId:string,input:Data){const range=tripMeta(input);return db.transaction(()=>{const id=randomUUID();db.run('INSERT INTO trips(id,title,start_date,end_date,time_zone) VALUES(?,?,?,?,?)',id,input.title.trim(),input.startDate,input.endDate,input.timeZone);db.run('INSERT INTO memberships VALUES(?,?,?)',id,userId,'owner');for(const date of ['',...range])db.run('INSERT INTO day_plans(trip_id,date) VALUES(?,?)',id,date);const name=db.get('SELECT username FROM users WHERE id=?',userId).username;put(userId,id,'participant',randomUUID(),{name,userId},0);return{id}})}
 function snapshot(userId:string,tripId:string):Snapshot{const role=access(userId,tripId);const t=db.get('SELECT * FROM trips WHERE id=?',tripId);return{tripId,title:t.title,startDate:t.start_date,endDate:t.end_date,timeZone:t.time_zone,version:t.version,archived:!!t.archived,seq:t.seq,role,entities:db.all('SELECT * FROM entities WHERE trip_id=? ORDER BY rowid',tripId).map(entity),days:db.all('SELECT * FROM day_plans WHERE trip_id=? ORDER BY date',tripId).map(d=>({date:d.date||null,version:d.version,itemIds:JSON.parse(d.item_ids)})),members:db.all('SELECT u.id,u.username,m.role FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.trip_id=?',tripId)}}
 function invite(userId:string,tripId:string,role:Role){access(userId,tripId,'manage');check(['editor','viewer'].includes(role),'邀请角色无效');const raw=token(),id=randomUUID();db.run('INSERT INTO invites(hash,id,trip_id,role,expires) VALUES(?,?,?,?,?)',digest(raw),id,tripId,role,Date.now()+7*86400000);return{id,token:raw}}
 function validInvite(raw:string){check(typeof raw==='string'&&raw.length<=100,'邀请无效');const inv=db.get('SELECT * FROM invites WHERE hash=?',digest(raw));check(inv,'邀请不存在',404);check(!inv.used,'邀请已被使用',409);check(!inv.revoked&&inv.expires>Date.now(),'邀请已失效',410);return inv}
 function accept(raw:string,credentials:{username?:string;password?:string},existingId?:string){return db.transaction(()=>{const inv=validInvite(raw);const user=existingId?db.get('SELECT id,username FROM users WHERE id=?',existingId):createUser(credentials.username!,credentials.password!);check(user,'请先登录',401);check(!db.get('SELECT 1 FROM memberships WHERE trip_id=? AND user_id=?',inv.trip_id,user.id),'你已经是同行人',409);db.run('INSERT INTO memberships VALUES(?,?,?)',inv.trip_id,user.id,inv.role);db.run('UPDATE invites SET used=1 WHERE hash=?',inv.hash);record(inv.trip_id,'membership',[user.id]);return{user,tripId:inv.trip_id}})}
 function removeMember(userId:string,tripId:string,target:string){db.transaction(()=>{access(userId,tripId,'manage');const row=db.get('SELECT role FROM memberships WHERE trip_id=? AND user_id=?',tripId,target);check(row&&row.role!=='owner','不能移除旅行拥有者');db.run('DELETE FROM memberships WHERE trip_id=? AND user_id=?',tripId,target);record(tripId,'membership',[target])});events.emit(tripId)}
 function record(tripId:string,kind:string,ids:string[]){db.run('UPDATE trips SET seq=seq+1 WHERE id=?',tripId);const seq=db.get('SELECT seq FROM trips WHERE id=?',tripId).seq;db.run('INSERT INTO trip_events VALUES(?,?,?,?)',tripId,seq,kind,JSON.stringify(ids));db.run('DELETE FROM trip_events WHERE trip_id=? AND seq<=?',tripId,seq-1000)}
 function refs(tripId:string,kind:Kind,d:Data){const exists=(id:string,k:Kind)=>!!db.get('SELECT 1 FROM entities WHERE id=? AND trip_id=? AND kind=?',id,tripId,k);const ids: [any,Kind][]=[];if(kind==='packing'&&d.participantId)ids.push([d.participantId,'participant']);if(kind==='expense'){ids.push([d.payer,'participant']);Object.keys(d.shares).forEach(id=>ids.push([id,'participant']))}if(kind==='settlement')ids.push([d.from,'participant'],[d.to,'participant']);if(kind==='guide')d.itemIds.forEach((id:string)=>ids.push([id,'item']));if(kind==='transport'){if(d.fromItemId)ids.push([d.fromItemId,'item']);if(d.toItemId)ids.push([d.toItemId,'item'])}check(ids.every(([id,k])=>typeof id==='string'&&exists(id,k)),'关联记录不存在或属于其他旅行');if(kind==='item'&&d.date)check(db.get('SELECT 1 FROM day_plans WHERE trip_id=? AND date=?',tripId,d.date),'事项日期不在旅行范围内')}
 function put(userId:string,tripId:string,kind:Kind,id:string,data:Data,version:number){const d=validateEntity(kind,data);refs(tripId,kind,d);db.run('INSERT INTO entities VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,version=excluded.version,updated_at=excluded.updated_at,updated_by=excluded.updated_by',id,tripId,kind,JSON.stringify(d),version+1,new Date().toISOString(),userId);return d}
 function day(tripId:string,date:string|null){const r=db.get('SELECT * FROM day_plans WHERE trip_id=? AND date=?',tripId,date||'');check(r,'目标日期不存在');return{...r,itemIds:JSON.parse(r.item_ids) as string[]}}
 function setDay(tripId:string,date:string|null,ids:string[]){db.run('UPDATE day_plans SET item_ids=?,version=version+1 WHERE trip_id=? AND date=?',JSON.stringify(ids),tripId,date||'')}
 function command(userId:string,tripId:string,c:Data){db.transaction(()=>{access(userId,tripId,'write');const t=db.get('SELECT * FROM trips WHERE id=?',tripId);check(typeof c.mutationId==='string'&&c.mutationId.length>=8&&c.mutationId.length<=100,'请求编号无效');const hash=digest(JSON.stringify(c));const prev=db.get('SELECT digest FROM mutation_receipts WHERE user_id=? AND trip_id=? AND mutation_id=?',userId,tripId,c.mutationId);if(prev){check(prev.digest===hash,'重复请求编号对应了不同内容',409);return}check(!t.archived||c.type==='updateTrip','已归档旅行为只读',409);
 if(c.type==='updateTrip'){access(userId,tripId,'manage');check(t.version===c.expectedVersion,'旅行已更新，请刷新',409);const range=tripMeta(c.data);const active=db.all("SELECT data FROM entities WHERE trip_id=? AND kind='item'",tripId).map(e=>JSON.parse(e.data).date);check(active.every(d=>!d||range.includes(d)),'新日期范围会排除已安排事项，请先移动事项');for(const d of range)db.run('INSERT OR IGNORE INTO day_plans(trip_id,date) VALUES(?,?)',tripId,d);for(const row of db.all('SELECT date FROM day_plans WHERE trip_id=?',tripId))if(row.date&&!range.includes(row.date))db.run('DELETE FROM day_plans WHERE trip_id=? AND date=?',tripId,row.date);db.run('UPDATE trips SET title=?,start_date=?,end_date=?,time_zone=?,archived=?,version=version+1 WHERE id=?',c.data.title,c.data.startDate,c.data.endDate,c.data.timeZone,c.data.archived?1:0,tripId);record(tripId,'trip',[])}else{
 check(typeof c.id==='string'&&/^[a-zA-Z0-9_-]{1,100}$/.test(c.id),'记录编号无效');const row=db.get('SELECT * FROM entities WHERE id=?',c.id);check(!row||row.trip_id===tripId,'记录属于其他旅行',403);if((row?.version||0)!==c.expectedVersion)throw new AppError('此项已由同行人更新，请核对最新内容',409,row?entity(row):null);check(!row||c.type==='moveItem'||row.kind===c.kind,'记录类型不匹配');
 if(c.type==='writeEntity'){const old=row?JSON.parse(row.data):null;const d=put(userId,tripId,c.kind,c.id,c.data,c.expectedVersion);if(c.kind==='item'&&(!old||old.date!==d.date)){if(old)setDay(tripId,old.date,day(tripId,old.date).itemIds.filter((x:string)=>x!==c.id));setDay(tripId,d.date,[...day(tripId,d.date).itemIds,c.id])}record(tripId,c.kind,[c.id])}
 else if(c.type==='deleteEntity'){check(row,'记录已删除',409);check(row.kind!=='participant','历史参与者不能删除，请改名或解除账号权限');if(row.kind==='item'){const d=JSON.parse(row.data);setDay(tripId,d.date,day(tripId,d.date).itemIds.filter((x:string)=>x!==c.id));for(const linked of db.all("SELECT * FROM entities WHERE trip_id=? AND kind IN ('guide','transport')",tripId)){const data=JSON.parse(linked.data);let changed=false;if(linked.kind==='guide'&&data.itemIds.includes(c.id)){data.itemIds=data.itemIds.filter((id:string)=>id!==c.id);changed=true}if(linked.kind==='transport')for(const k of ['fromItemId','toItemId'])if(data[k]===c.id){data[k]=null;changed=true}if(changed)put(userId,tripId,linked.kind,linked.id,data,linked.version)}}db.run('DELETE FROM entities WHERE id=?',c.id);record(tripId,row.kind,[c.id])}
 else if(c.type==='moveItem'){check(row?.kind==='item','事项不存在');const d=JSON.parse(row.data),from=day(tripId,d.date),to=day(tripId,c.date);check(from.version===c.fromDayVersion&&to.version===c.toDayVersion,'日期排序已更新，请刷新',409);const dest=to.itemIds.filter((x:string)=>x!==c.id);const idx=c.beforeId?dest.indexOf(c.beforeId):dest.length;check(idx>=0,'排序位置已变化',409);dest.splice(idx,0,c.id);if(d.date!==c.date)setDay(tripId,d.date,from.itemIds.filter((x:string)=>x!==c.id));setDay(tripId,c.date,dest);put(userId,tripId,'item',c.id,{...d,date:c.date},row.version);record(tripId,'item',[c.id])}
 else throw new AppError('不支持的操作');}
 db.run('INSERT INTO mutation_receipts VALUES(?,?,?,?)',userId,tripId,c.mutationId,hash);
 });events.emit(tripId);return snapshot(userId,tripId)}
 return{db,events,createUser,login,session,access,createTrip,snapshot,invite,accept,validInvite,removeMember,command,record,close:()=>db.close()};
}
export type Service=ReturnType<typeof createService>;
